version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - "DJANGO_SECRET_KEY=x2&z9s$$vd11((_f7i^ov4-fh^%w#gt9_9y-$$-of5qf#^6&i-$$h"
      - "DJANGO_DEBUG=True"
    
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"